In [1]:
import rasterio
# 导入必要的库和函数
from pathlib import Path
from functions import productivity_land_cover_classification
import pandas as pd
import os

with rasterio.open("../data/Land_Cover_Each_Year/C3S_2015_reclass_300m.tif") as src:
    data = src.read(1)
    profile = src.profile
    print(profile)
    crs = src.crs
    print(crs)
    transform = src.transform
    print(transform)
    bounds = src.bounds
    print(bounds)
    count = src.count
    print(count)
    nodata = src.nodata
    print(nodata)

{'driver': 'GTiff', 'dtype': 'int16', 'nodata': -32768.0, 'width': 1813, 'height': 1277, 'count': 1, 'crs': CRS.from_wkt('GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AXIS["Latitude",NORTH],AXIS["Longitude",EAST],AUTHORITY["EPSG","4326"]]'), 'transform': Affine(0.0026949458523585646, 0.0, 51.49772029271981,
       0.0, -0.0026949458523585646, 26.070906175716754), 'blockxsize': 256, 'blockysize': 256, 'tiled': True, 'compress': 'deflate', 'interleave': 'band'}
EPSG:4326
| 0.00, 0.00, 51.50|
| 0.00,-0.00, 26.07|
| 0.00, 0.00, 1.00|
BoundingBox(left=51.49772029271981, bottom=22.629460322254868, right=56.38365712304589, top=26.070906175716754)
1
-32768.0

In [2]:
# 定义输入文件路径
land_cover_path = Path("../data/Land_Cover_Each_Year/C3S_2015_reclass_300m.tif")
productivity_bins = Path("../output/trend/2015/bins.tif")

# 定义土地覆盖类别名称映射（根据实际数据调整）
# 这里是一个示例映射，您需要根据实际的土地覆盖类别数值来调整

land_cover_class_names = {
    1: "Tree-covered areas",
    2: "Grasslands",
    3: "Croplands",
    4: "Wetlands",
    5: "Artificial surfaces",
    6: "Other Lands",
    7: "Water bodies",
}

# 调用函数生成统计表格
df = productivity_land_cover_classification(
    land_cover_path=land_cover_path,
    productivity_bins=productivity_bins,
    land_cover_class_names=land_cover_class_names,  # 可以传入None使用默认数值名称
)

# 显示结果表格
print("Net land productivity trend dynamic (km²) for the baseline period")
print("=" * 80)
os.makedirs("../output/appendix/trend",exist_ok=True)
df.to_csv("../output/appendix/trend/2015_trend.csv")
df

[1 2 3 4 5 6 7]
Net land productivity trend dynamic (km²) for the baseline period
================================================================================

      Land Cover Class  Degraded (km²)  Non-Degraded (km²)  No Data (km²)
0   Tree-covered areas           10.75              169.39          57.40
1           Grasslands           84.54             3244.08          98.23
2            Croplands          693.05             1851.17           9.69
3             Wetlands            3.31               46.64          35.27
4  Artificial surfaces          193.40             2467.74         113.30
5          Other Lands          747.82            61468.25         284.00
6         Water bodies            1.75              101.04         424.37

In [3]:
# 定义输入文件路径
land_cover_path = Path("../data/Land_Cover_Each_Year/C3S_2015_reclass_300m.tif")
productivity_bins = Path("../output/state/2015/bins.tif")

# 定义土地覆盖类别名称映射（根据实际数据调整）
# 这里是一个示例映射，您需要根据实际的土地覆盖类别数值来调整

land_cover_class_names = {
    1: "Tree-covered areas",
    2: "Grasslands",
    3: "Croplands",
    4: "Wetlands",
    5: "Artificial surfaces",
    6: "Other Lands",
    7: "Water bodies",
}

# 调用函数生成统计表格
df = productivity_land_cover_classification(
    land_cover_path=land_cover_path,
    productivity_bins=productivity_bins,
    land_cover_class_names=land_cover_class_names,  # 可以传入None使用默认数值名称
)

# 显示结果表格
print("Net land productivity state dynamic (km²) for the baseline period")
print("=" * 80)
os.makedirs("../output/appendix/state",exist_ok=True)
df.to_csv("../output/appendix/state/2015_state.csv")
df

[1 2 3 4 5 6 7]
Net land productivity state dynamic (km²) for the baseline period
================================================================================

      Land Cover Class  Degraded (km²)  Non-Degraded (km²)  No Data (km²)
0   Tree-covered areas            9.75              170.39          57.40
1           Grasslands           53.77             3274.84          98.23
2            Croplands          408.74             2135.48           9.69
3             Wetlands            0.63               49.33          35.27
4  Artificial surfaces          103.92             2557.22         113.30
5          Other Lands          332.70            61883.37         284.00
6         Water bodies            2.69              100.11         424.37

In [5]:

# 定义输入文件路径
land_cover_path = Path("../data/Land_Cover_Each_Year/C3S_2015_reclass_300m.tif")
productivity_bins = Path("../output/performance/2015/bins.tif")

# 定义土地覆盖类别名称映射（根据实际数据调整）
# 这里是一个示例映射，您需要根据实际的土地覆盖类别数值来调整

land_cover_class_names = {
    1: "Tree-covered areas",
    2: "Grasslands",
    3: "Croplands",
    4: "Wetlands",
    5: "Artificial surfaces",
    6: "Other Lands",
    7: "Water bodies",
}

# 调用函数生成统计表格
df = productivity_land_cover_classification(
    land_cover_path=land_cover_path,
    productivity_bins=productivity_bins,
    land_cover_class_names=land_cover_class_names,  # 可以传入None使用默认数值名称
)

# 显示结果表格
print("Net land productivity performance dynamic (km²) for the baseline period")
print("=" * 80)
os.makedirs("../output/appendix/performance",exist_ok=True)
df.to_csv("../output/appendix/performance/2015_performance.csv")
df

[1 2 3 4 5 6 7]
Net land productivity performance dynamic (km²) for the baseline period
================================================================================

      Land Cover Class  Degraded (km²)  Non-Degraded (km²)  No Data (km²)
0   Tree-covered areas           13.63               29.51         194.40
1           Grasslands          136.62             3062.37         227.85
2            Croplands            0.69             2452.55         100.67
3             Wetlands            3.75                6.94          74.53
4  Artificial surfaces          119.05             2340.56         314.82
5          Other Lands          326.64            61342.07         831.36
6         Water bodies           15.88               11.63         499.65

In [11]:
# 导入土地转换函数
from functions import land_cover_conversion_productivity

# 定义输入文件路径
# 初始土地覆盖（基准期）
initial_land_cover_path = Path("../data/Land_Cover_Each_Year/C3S_2000_reclass_300m.tif")
# 最终土地覆盖（评估期）
final_land_cover_path = Path("../data/Land_Cover_Each_Year/C3S_2015_reclass_300m.tif")
# 生产力bins（根据需要的指标选择：trend/state/performance）
productivity_bins = Path("../output/state/2015/bins.tif")

# 定义土地覆盖类别名称映射（简化名称，便于表格显示）
land_cover_class_names = {
    1: "Forest",
    2: "Grassland",
    3: "Cropland",
    4: "Wetland",
    5: "Artificial",
    6: "Other",
    7: "Water",
}

# 定义输出目录
output_dir = Path("../output/appendix/land_conversation")
output_dir.mkdir(parents=True, exist_ok=True)

# 调用函数生成土地转换统计表格
df_conversion = land_cover_conversion_productivity(
    initial_land_cover_path=initial_land_cover_path,
    final_land_cover_path=final_land_cover_path,
    productivity_bins=productivity_bins,
    land_cover_class_names=land_cover_class_names,
    output_dir=output_dir,  # 保存到指定目录
)

# 显示结果表格
print("Net land productivity stable dynamics (km²) for the baseline period")
print("=" * 80)
print(df_conversion.to_string(index=False))
df_conversion.to_csv("../output/appendix/state/2015_state_conversion.csv")
print("=" * 80)

Land cover conversion table saved to: ../output/appendix/land_conversation/land_conversion_C3S_2000_reclass_300m_to_C3S_2015_reclass_300m_bins.csv
Net land productivity stable dynamics (km²) for the baseline period
================================================================================
      From         To  Declining (km²)  Moderate Decline (km²)  Stressed (km²)  Stable (km²)  Increasing (km²)
    Forest     Forest              9.7                    18.9            33.1          62.7              45.1
    Forest Artificial              0.0                     0.0             0.3           0.1               0.1
 Grassland  Grassland             53.8                   922.0          1422.1         822.4              90.4
 Grassland   Cropland              0.1                     0.4             0.0           0.0               0.0
 Grassland Artificial              0.2                     1.9             2.1           2.6               0.4
 Grassland      Other              1.6                    19.1            35.7           8.9               1.1
  Cropland  Grassland              0.0                     0.0             0.0           0.1               0.0
  Cropland   Cropland            407.5                   794.7           621.6         515.2             198.7
  Cropland Artificial              0.4                     1.9             3.9           3.9               0.8
  Cropland      Other              3.8                     1.6             0.4           0.0               0.0
   Wetland    Wetland              0.6                     6.3             8.1          14.3              13.2
Artificial Artificial            101.5                   455.6           727.2         912.0             403.2
     Other  Grassland              0.0                     2.8            11.8           2.6               0.2
     Other   Cropland              1.1                     0.6             1.0           1.6               1.7
     Other Artificial              1.8                     5.8             7.9          12.7              14.9
     Other      Other            327.3                  2149.2         35873.8       22941.8             847.2
     Other      Water              0.0                     0.1             0.1           0.0               0.0
     Water     Forest              0.1                     0.6             0.8           2.4               6.8
     Water  Grassland              0.0                     0.1             0.1           0.2               0.1
     Water    Wetland              0.0                     0.1             0.2           2.6               4.6
     Water Artificial              0.0                     0.0             0.1           0.0               0.0
     Water      Other              0.1                     0.8             0.7           1.6               1.6
     Water      Water              2.7                    14.7            30.0          39.6              15.8
================================================================================

In [12]:
# 定义输入文件路径
# 初始土地覆盖（基准期）
initial_land_cover_path = Path("../data/Land_Cover_Each_Year/C3S_2000_reclass_300m.tif")
# 最终土地覆盖（评估期）
final_land_cover_path = Path("../data/Land_Cover_Each_Year/C3S_2015_reclass_300m.tif")
# 生产力bins（根据需要的指标选择：trend/state/performance）
productivity_bins = Path("../output/trend/2015/bins.tif")

# 定义土地覆盖类别名称映射（简化名称，便于表格显示）
land_cover_class_names = {
    1: "Forest",
    2: "Grassland",
    3: "Cropland",
    4: "Wetland",
    5: "Artificial",
    6: "Other",
    7: "Water",
}

# 定义输出目录
output_dir = Path("../output/appendix/land_conversation")
output_dir.mkdir(parents=True, exist_ok=True)

# 调用函数生成土地转换统计表格
df_conversion = land_cover_conversion_productivity(
    initial_land_cover_path=initial_land_cover_path,
    final_land_cover_path=final_land_cover_path,
    productivity_bins=productivity_bins,
    land_cover_class_names=land_cover_class_names,
    output_dir=output_dir,  # 保存到指定目录
)

# 显示结果表格
print("Net land productivity stable dynamics (km²) for the baseline period")
print("=" * 80)
print(df_conversion.to_string(index=False))
df_conversion.to_csv("../output/appendix/trend/2015_trend_conversion.csv")
print("=" * 80)

Land cover conversion table saved to: ../output/appendix/land_conversation/land_conversion_C3S_2000_reclass_300m_to_C3S_2015_reclass_300m_bins.csv
Net land productivity stable dynamics (km²) for the baseline period
================================================================================
      From         To  Declining (km²)  Moderate Decline (km²)  Stressed (km²)  Stable (km²)  Increasing (km²)
    Forest     Forest             10.7                    21.1            31.5          55.6              50.6
    Forest Artificial              0.0                     0.1             0.1           0.2               0.1
 Grassland  Grassland             84.5                   736.3          1087.2        1132.1             270.6
 Grassland   Cropland              0.4                     0.1             0.0           0.0               0.0
 Grassland Artificial              0.9                     1.5             1.9           1.9               0.9
 Grassland      Other             13.9                    21.8            12.5          12.1               6.1
  Cropland  Grassland              0.0                     0.0             0.0           0.0               0.1
  Cropland   Cropland            692.0                   616.7           314.6         393.2             521.2
  Cropland Artificial              0.8                     2.1             1.9           3.3               2.9
  Cropland      Other              4.5                     1.0             0.2           0.0               0.0
   Wetland    Wetland              3.3                     6.3             6.7          13.4              12.8
Artificial Artificial            188.7                   454.9           385.0         618.3             952.7
     Other  Grassland              0.1                     1.2             8.0           7.7               0.4
     Other   Cropland              0.6                     1.2             0.6           0.9               2.7
     Other Artificial              3.0                     4.4             5.7           8.2              21.8
     Other      Other            729.2                  4327.7         10814.4       28515.6           17752.2
     Other      Water              0.1                     0.1             0.0           0.0               0.0
     Water     Forest              0.1                     0.4             1.0           3.3               5.8
     Water  Grassland              0.0                     0.1             0.2           0.2               0.0
     Water    Wetland              0.0                     0.1             0.4           1.9               5.1
     Water Artificial              0.0                     0.0             0.1           0.0               0.0
     Water      Other              0.1                     0.6             0.7           1.3               2.0
     Water      Water              1.7                    14.6            26.8          39.8              19.8
================================================================================

In [13]:
# 定义输入文件路径
# 初始土地覆盖（基准期）
initial_land_cover_path = Path("../data/Land_Cover_Each_Year/C3S_2000_reclass_300m.tif")
# 最终土地覆盖（评估期）
final_land_cover_path = Path("../data/Land_Cover_Each_Year/C3S_2015_reclass_300m.tif")
# 生产力bins（根据需要的指标选择：trend/state/performance）
productivity_bins = Path("../output/performance/2015/bins.tif")

# 定义土地覆盖类别名称映射（简化名称，便于表格显示）
land_cover_class_names = {
    1: "Forest",
    2: "Grassland",
    3: "Cropland",
    4: "Wetland",
    5: "Artificial",
    6: "Other",
    7: "Water",
}

# 定义输出目录
output_dir = Path("../output/appendix/land_conversation")
output_dir.mkdir(parents=True, exist_ok=True)

# 调用函数生成土地转换统计表格
df_conversion = land_cover_conversion_productivity(
    initial_land_cover_path=initial_land_cover_path,
    final_land_cover_path=final_land_cover_path,
    productivity_bins=productivity_bins,
    land_cover_class_names=land_cover_class_names,
    output_dir=output_dir,  # 保存到指定目录
)

# 显示结果表格
print("Net land productivity stable dynamics (km²) for the baseline period")
print("=" * 80)
print(df_conversion.to_string(index=False))
df_conversion.to_csv("../output/appendix/performance/2015_performance_conversion.csv")
print("=" * 80)

Land cover conversion table saved to: ../output/appendix/land_conversation/land_conversion_C3S_2000_reclass_300m_to_C3S_2015_reclass_300m_bins.csv
Net land productivity stable dynamics (km²) for the baseline period
================================================================================
      From         To  Declining (km²)  Moderate Decline (km²)  Stressed (km²)
    Forest     Forest             12.8                    19.8             8.3
    Forest Artificial              0.1                     0.1             0.0
 Grassland  Grassland            136.5                  2863.4           181.5
 Grassland   Cropland              0.0                     0.0             0.5
 Grassland Artificial              0.1                     3.9             2.3
 Grassland      Other              0.0                    48.5            17.8
  Cropland  Grassland              0.0                     0.0             0.1
  Cropland   Cropland              0.7                   422.3          2023.7
  Cropland Artificial              0.0                     1.9             8.6
  Cropland      Other              0.0                     0.4             5.3
   Wetland    Wetland              3.0                     2.1             4.3
Artificial Artificial            117.7                  1672.7           612.2
     Other  Grassland              0.0                    16.5             0.9
     Other   Cropland              0.0                     0.2             5.8
     Other Artificial              1.2                    33.4             5.6
     Other      Other            326.0                 57276.6          3993.3
     Other      Water              0.1                     0.0             0.0
     Water     Forest              0.9                     0.9             0.6
     Water  Grassland              0.1                     0.1             0.0
     Water    Wetland              0.8                     0.3             0.3
     Water      Other              0.7                     0.2             0.0
     Water      Water             15.8                     5.5             6.1
================================================================================